/*
JavaScript Brief Slideshow 1.0
(C)1999-2008 Usingit.com, All rights reserved!
http://www.usingit.com/products/webtoolkit
http://www.usingit.com/support
*/
var BriefSlideshow1PropsArray = [
['./pictures/slider0.jpg','javascript:void(0)','_self',,,'This script was generated by JavaScript Brief Slideshow from usingit.com!'],
['./pictures/slider1.jpg','javascript:void(0)','_self','Lecture Halls','lecture halls with full facilities','This script was generated by JavaScript Brief Slideshow from usingit.com!']

];
function startBriefSlideshow1(){
var BriefSlideshow1 = new bUar('BriefSlideshow1',BriefSlideshow1PropsArray,65,3000,1000,50,1000,50,1000,1000);
}
bdas(startBriefSlideshow1);
